Iso20022 DEFINITIONS AUTOMATIC TAGS ::= BEGIN

    Country ::= UTF8String --1.3.6.1.4.1.62675.1.2.0
    CountrySubDivision ::= UTF8String --1.3.6.1.4.1.62675.1.2.1
    PostalCode ::= UTF8String --1.3.6.1.4.1.62675.1.2.3
    TownName ::= UTF8String --1.3.6.1.4.1.62675.1.2.4
    BuildingNumber ::= UTF8String --1.3.6.1.4.1.62675.1.2.5
    StreetName ::= UTF8String --1.3.6.1.4.1.62675.1.2.6
    AddressLines ::= SEQUENCE OF UTF8String --1.3.6.1.4.1.62675.1.2.7
    SubDepartment ::= UTF8String --1.3.6.1.4.1.62675.1.2.8
    Department ::= UTF8String --1.3.6.1.4.1.62675.1.2.9
    EmailAddressPurpose ::= UTF8String --1.3.6.1.4.1.62675.1.3.0
    FullName ::= UTF8String --1.3.6.1.4.1.62675.1.0
    BirthDate ::= GeneralizedTime --1.3.6.1.4.1.62675.1.1
    EmailAddress ::= UTF8String --1.3.6.1.4.1.62675.1.3
    PhoneNumber ::= UTF8String --1.3.6.1.4.1.62675.1.4
    JobTitle ::= UTF8String --1.3.6.1.4.1.62675.1.6
    JobResponsibility ::= UTF8String --1.3.6.1.4.1.62675.1.6.1
    Id ::= UTF8String     --1.3.6.1.4.1.62675.1.7
    Issuer ::= UTF8String --1.3.6.1.4.1.62675.1.7.1

    AddressType ::= CHOICE { -- 1.3.6.1.4.1.62675.1.2.10
        code              [0] IMPLICIT UTF8String,
        proprietary       [1] IMPLICIT UTF8String
    }

    OrganizationIdentificationSchemeNameChoice ::= CHOICE { -- 1.3.6.1.4.1.62675.1.8.0.2
        code              [0] IMPLICIT UTF8String,
        proprietary       [1] IMPLICIT UTF8String
    }

    PersonIdentificationSchemeNameChoice ::= CHOICE { -- 1.3.6.1.4.1.62675.1.8.1.1
        code              [0] IMPLICIT UTF8String,
        proprietary       [1] IMPLICIT UTF8String
    }

    Address ::= SEQUENCE { --1.3.6.1.4.1.62675.1.2
        addressLines      AddressLines OPTIONAL,
        addressType       AddressType OPTIONAL,
        buildingNumber    BuildingNumber OPTIONAL,
        country           Country OPTIONAL,
        countrySubDivision CountrySubDivision OPTIONAL,
        department        Department OPTIONAL,
        postalCode        PostalCode OPTIONAL,
        streetName        StreetName OPTIONAL,
        subDepartment     SubDepartment OPTIONAL,
        townName          TownName OPTIONAL
    }

    DateAndPlaceOfBirth ::= SEQUENCE { --1.3.6.1.4.1.62675.1.5
        birthDate         BirthDate,
        cityOfBirth       TownName,
        countryOfBirth    Country,
        provinceOfBirth   CountrySubDivision OPTIONAL
    }

    ContactDetails ::= SEQUENCE { --1.3.6.1.4.1.62675.1.9
        department        Department OPTIONAL,
        emailAddress      EmailAddress OPTIONAL,
        emailPurpose      EmailAddressPurpose OPTIONAL,
        faxNumber         PhoneNumber OPTIONAL,
        fullName          FullName OPTIONAL,
        jobResponsibility JobResponsibility OPTIONAL,
        jobTitle          JobTitle OPTIONAL,
        mobileNumber      PhoneNumber OPTIONAL,
        namePrefix        NamePrefixCode OPTIONAL,
        other             SEQUENCE OF OtherContact OPTIONAL,
        phoneNumber       PhoneNumber OPTIONAL,
        preferredMethod   PreferredContactMethodCode OPTIONAL
    }

    OrganizationIdentification ::= SEQUENCE { --1.3.6.1.4.1.62675.1.8.0
        bic               UTF8String OPTIONAL,
        lei               UTF8String OPTIONAL,
        other             SEQUENCE OF GenericOrganizationIdentification OPTIONAL
    }

    GenericOrganizationIdentification ::= SEQUENCE { --1.3.6.1.4.1.62675.1.8.0.1
        id                Id,
        issuer            Issuer OPTIONAL,
        schemeName        OrganizationIdentificationSchemeNameChoice OPTIONAL
    }

    PersonIdentification ::= SEQUENCE { --1.3.6.1.4.1.62675.1.8.1
        dateAndPlaceOfBirth DateAndPlaceOfBirth OPTIONAL,
        other             SEQUENCE OF GenericPersonIdentification OPTIONAL
    }

    GenericPersonIdentification ::= SEQUENCE { --1.3.6.1.4.1.62675.1.8.1.0
        id                Id,
        issuer            Issuer OPTIONAL,
        schemeName        PersonIdentificationSchemeNameChoice OPTIONAL
    }

    OtherContact ::= SEQUENCE { --1.3.6.1.4.1.62675.1.9.1
        channelType       UTF8String,
        id                Id OPTIONAL
    }

    EntityType ::= CHOICE { --1.3.6.1.4.1.62675.1.8
        organization      [0] IMPLICIT OrganizationIdentification,
        person            [1] IMPLICIT PersonIdentification
    }

    NamePrefixCode ::= ENUMERATED { --1.3.6.1.4.1.62675.1.0.0
        DOCT, MIST, MISS, MIKS, MME
    }

    PreferredContactMethodCode ::= ENUMERATED { --1.3.6.1.4.1.62675.1.9.0
        LETT, MAIL, PHON, FAXX, CELL
    }

END
