//! Generated ASN.1 code
//!
//! This module contains all the generated ASN.1 structures and re-exports them
//! for use throughout the library.
//!
//! This file is automatically generated by build.rs - do not edit manually.

#[allow(unused_imports, unused_variables, dead_code, non_camel_case_types, clippy::too_many_arguments)]
mod algorithm_identifier_definitions {
	include!(concat!(env!("OUT_DIR"), "/generated/algorithm_identifier_definitions.rs"));
}
#[allow(unused_imports, unused_variables, dead_code, non_camel_case_types, clippy::too_many_arguments)]
pub mod iso20022 {
	include!(concat!(env!("OUT_DIR"), "/generated/iso20022.rs"));
}
#[allow(unused_imports, unused_variables, dead_code, non_camel_case_types, clippy::too_many_arguments)]
mod subject_public_key_info_definitions {
	include!(concat!(env!("OUT_DIR"), "/generated/subject_public_key_info_definitions.rs"));
}

// Re-export all types from the generated modules
pub use algorithm_identifier_definitions::AlgorithmIdentifier;
pub use subject_public_key_info_definitions::SubjectPublicKeyInfo;
