//! Wire-compatibility fixtures generated by the reference TypeScript
//! implementation (`tests/generate_fixtures.cjs`).
//!
//! Every vector is decoded, re-encoded and hashed; all bytes must match the
//! reference exactly.

use keetanetwork_block::{Block, BlockPurpose, BlockVersion, Hashable, UnsignedBlock};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
	name: String,
	bytes: String,
	unsigned_bytes: String,
	hash: String,
	version: u8,
	purpose: u8,
	network: String,
	subnet: Option<String>,
	idempotent: Option<String>,
	date_ms: i64,
	account: String,
	previous: String,
	operation_count: usize,
	signature_count: usize,
	signatures: Vec<String>,
}

fn fixtures() -> Vec<Fixture> {
	let raw = include_str!("fixtures/blocks.json");
	serde_json::from_str(raw).expect("fixtures must parse")
}

fn decode_signed(fixture: &Fixture) -> Block {
	let bytes = hex::decode(&fixture.bytes).expect("fixture bytes must be hex");
	Block::try_from(bytes.as_slice()).unwrap_or_else(|error| panic!("fixture {} must decode: {error}", fixture.name))
}

fn decode_unsigned(fixture: &Fixture) -> UnsignedBlock {
	let bytes = hex::decode(&fixture.unsigned_bytes).expect("fixture bytes must be hex");
	UnsignedBlock::try_from(bytes.as_slice())
		.unwrap_or_else(|error| panic!("fixture {} must decode unsigned: {error}", fixture.name))
}

#[test]
fn test_fixture_blocks_decode_and_reencode() {
	let fixtures = fixtures();
	assert!(!fixtures.is_empty(), "fixture set must not be empty");

	for fixture in &fixtures {
		let block = decode_signed(fixture);

		assert_eq!(
			hex::encode_upper(block.to_bytes()),
			fixture.bytes,
			"fixture {} re-encoded bytes must match",
			fixture.name
		);
		assert_eq!(block.hash().to_string(), fixture.hash, "fixture {} hash must match", fixture.name);
	}
}

#[test]
fn test_fixture_unsigned_blocks_decode_and_reencode() {
	for fixture in &fixtures() {
		let unsigned = decode_unsigned(fixture);

		assert_eq!(
			hex::encode_upper(unsigned.to_bytes()),
			fixture.unsigned_bytes,
			"fixture {} unsigned bytes must match",
			fixture.name
		);
		assert_eq!(unsigned.hash().to_string(), fixture.hash, "fixture {} unsigned hash must match", fixture.name);
	}
}

#[test]
fn test_fixture_fields_match() {
	for fixture in &fixtures() {
		let block = decode_signed(fixture);
		let data = block.data();

		let version = match data.version() {
			BlockVersion::V1 => 1,
			BlockVersion::V2 => 2,
		};
		assert_eq!(version, fixture.version, "fixture {} version", fixture.name);

		let purpose = match data.purpose() {
			BlockPurpose::Generic => 0,
			BlockPurpose::Fee => 1,
		};
		assert_eq!(purpose, fixture.purpose, "fixture {} purpose", fixture.name);

		assert_eq!(data.network().to_string(), fixture.network, "fixture {} network", fixture.name);
		assert_eq!(data.subnet().map(|subnet| subnet.to_string()), fixture.subnet, "fixture {} subnet", fixture.name);
		assert_eq!(data.idempotent().map(hex::encode_upper), fixture.idempotent, "fixture {} idempotent", fixture.name);
		assert_eq!(data.date().unix_millis(), fixture.date_ms, "fixture {} date", fixture.name);
		assert_eq!(data.account().to_string(), fixture.account, "fixture {} account", fixture.name);
		assert_eq!(data.previous().to_string(), fixture.previous, "fixture {} previous", fixture.name);
		assert_eq!(data.operations().len(), fixture.operation_count, "fixture {} operation count", fixture.name);
		assert_eq!(block.signatures().len(), fixture.signature_count, "fixture {} signature count", fixture.name);

		let signatures: Vec<String> = block
			.signatures()
			.iter()
			.map(|s| hex::encode_upper(s.as_ref()))
			.collect();
		assert_eq!(signatures, fixture.signatures, "fixture {} signatures", fixture.name);
	}
}

#[test]
fn test_fixture_corrupted_signature_rejected() {
	for fixture in &fixtures() {
		let mut bytes = hex::decode(&fixture.bytes).expect("fixture bytes must be hex");
		let last = bytes.len() - 1;
		bytes[last] ^= 0xFF;

		assert!(
			Block::try_from(bytes.as_slice()).is_err(),
			"fixture {} with corrupted signature must be rejected",
			fixture.name
		);
	}
}
