//! SDK Compatibility Tests
//!
//! These tests parse block DER bytes from .hex files and verify roundtrip encoding.
//! Test data is from mainnet blocks generated by @keetanetwork/keetanet-client JS SDK.

use der::{Decode, Encode};
use keetanetwork_block::KeetaBlock;
use std::fs;
use std::path::PathBuf;

fn get_samples_dir() -> PathBuf {
	PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/samples")
}

fn load_block_hex(name: &str) -> Vec<u8> {
	let path = get_samples_dir().join(format!("{}.hex", name));
	let content = fs::read_to_string(&path).expect(&format!("Failed to read {}", path.display()));

	// Filter out comment lines and empty lines
	let hex: String = content
		.lines()
		.filter(|line| !line.starts_with("//") && !line.trim().is_empty())
		.collect();

	hex::decode(&hex).expect(&format!("Invalid hex in {}", path.display()))
}

/// Block samples to test.
const SAMPLES: &[&str] = &[
	"SET_REP",
	"SET_INFO",
	"CREATE_IDENTIFIER",
	"TOKEN_ADMIN_SUPPLY",
	"SEND",
	"SWAP",
	"RECEIVE",
	"MANAGE_CERTIFICATE",
];

#[test]
fn test_block_roundtrip_all_samples() {
	for sample_name in SAMPLES {
		let original_bytes = load_block_hex(sample_name);

		let block = KeetaBlock::from_der(&original_bytes).expect(&format!("Failed to parse {} block", sample_name));

		assert!(!block.operations.is_empty(), "{} block should have operations", sample_name);
		assert!(!block.signatures.is_empty(), "{} block should have signatures", sample_name);

		let encoded = block
			.to_der()
			.expect(&format!("Failed to encode {} block", sample_name));

		assert_eq!(encoded, original_bytes, "Roundtrip encoding mismatch for {} block", sample_name);
	}
}
